Fix TorchFT trainer CUDA graph integration (#4518)
Stack from [ghstack](https://github.com/ezyang/ghstack/tree/0.15.0)
(oldest at bottom):
* __->__ #4518

Port the updated `wrap_with_cuda_graph` to torchft trainer.
This fixes the error

```
File "/pytorch/torchtitan/torchtitan/experiments/torchft/trainer.py", line 314, in __init__
  self.fwd_bwd_fn = wrap_with_cuda_graph(self.fwd_bwd_fn)
		    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: wrap_with_cuda_graph() missing 3 required keyword-only arguments: 'gradient_accumulation_steps', 'sdc_num_steps', and 'sdc_num_replays'
```

Co-authored-by: Tushar Jain <tushar00jain@users.noreply.github.com>