Fix TorchFT trainer CUDA graph integration
Port the updated `wrap_with_cuda_graph` to torchft trainer.
This fixes the error

```
File "/pytorch/torchtitan/torchtitan/experiments/torchft/trainer.py", line 314, in __init__
  self.fwd_bwd_fn = wrap_with_cuda_graph(self.fwd_bwd_fn)
		    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: wrap_with_cuda_graph() missing 3 required keyword-only arguments: 'gradient_accumulation_steps', 'sdc_num_steps', and 'sdc_num_replays'
```

ghstack-source-id: da66ba38063d602bd7af588e37cc9c28e18261ac
Pull-Request: https://github.com/pytorch/torchtitan/pull/4518