[spmd_types] Qwen3.5 spmd_typecheck error fix (#4179)
Running `qwen35_debugmodel` with TP 2 + DP 2 spmd_types backend with
typecheck gave an error
```
File "/data/users/jinsooihm/mywork/torchtitan-qwen35-fold/torchtitan/models/qwen3_5/model.py", line 431, in forward
      xq_BLNK = self._causal_conv(
                ^^^^^^^^^^^^^^^^^^
    File "/data/users/jinsooihm/mywork/torchtitan-qwen35-fold/torchtitan/models/qwen3_5/model.py", line 353, in _causal_conv
      return _causal_conv1d_varlen(
             ^^^^^^^^^^^^^^^^^^^^^^
 ...
      raise SpmdTypeError(
  spmd_types.types.SpmdTypeError: PartitionSpec conflict: axis mesh_dp already shards dim 0, cannot also shard dim 1
```

This is because `fold_bl_dim` reshaped the tensor to `[1, B * L, ...]`
but the type did not propagate to specify shard on dim 1.
Separated as a local_map following the form of `unflatten_to_bld`. 

No integration test actually tested for qwen35 with spmd typecheck
because one has PP and the other has AC.

## Test Plan
```
NGPU=4 MODULE=qwen3_5 CONFIG=qwen35_debugmodel \                                             
  run_train.sh \
    --parallelism.tensor_parallel_degree 2 \
    --parallelism.data_parallel_shard_degree 2 \
    --parallelism.spmd_backend spmd_types \
    --debug.seed=42 --debug.deterministic \
    --training.disable_cuda_graphs \
    activation-checkpoint:none
```
gives identical loss for 10 steps compared with the commit
https://github.com/pytorch/torchtitan/commit/c82675eb6eed7a9930791463d6fbaece2d979ef5.
Also, running with `--debug.spmd_typechecking` passes now.