realign scaled grouped gemm api with torchao (#2460)
After TorchAO reconfigured their moe_training, the api for fp8 scaled
grouped gemm changed to FP8GroupedMMConfig and mxfp8 changed to
MXFP8GroupedMMConfig
Changing naming to reflect the change.

Changes were tested on mi300x, fp8 grouped gemm test successfully
passes. with model_converters setting on deepseek_v3_16b:
`model_converters=ModelConvertersContainer.Config(
            converters=[
                Float8GroupedMMConverter.Config(fqns=["experts"]),
            ],
        )`

mxfp8 grouped gemm does not work on mi300x, however, I can confirm that
after the change with model converter on deepseek_v3_16b:
deepseek_v3_16b:
`model_converters=ModelConvertersContainer.Config(
            converters=[
                MXGroupedMMConverter.Config(fqns=["experts"]),
            ],
        )`

enters the new TorchAO path for mxfp8_grouped_mm.py
`
File
"/home/AMD/aminooka/miniforge3/envs/torchtitan72/lib/python3.12/site-packages/torchao/prototype/moe_training/mxfp8_grouped_mm.py",
line 141, in forward
      assert emulated or _SM100_KERNELS_AVAILABLE, (
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: SM100 kernels not available. Please use use torchao CUDA
12.8+ build on SM100/100a device(s). Otherwise, set
kernel_preference=KernelPreference.EMULATED (emulated mode implements
basic functionality without efficient kernels).
`

---------

Co-authored-by: Alex Minooka <aminooka@amd.com>